// ============================================================
//  HAMMER — ALL GAME DATA
// ============================================================

const GAMES_DATA = [
  // ── ORIGINAL GAMES ──────────────────────────────────────
  { id:"life-clock",       title:"Life Clock",           emoji:"⏳", description:"See how much time you've spent — and have left.",                          color:"#FF6B35", tag:"reflective",  category:"Mind" },
  { id:"spend-billion",    title:"Spend a Billion",      emoji:"💸", description:"You have $1,000,000,000. Spend it all.",                                    color:"#2EC4B6", tag:"interactive", category:"Fun" },
  { id:"password-game",    title:"Password Chaos",       emoji:"🔐", description:"Create a password that meets increasingly absurd rules.",                    color:"#E71D36", tag:"game",        category:"Games" },
  { id:"universe-size",    title:"Size of Universe",     emoji:"🌌", description:"Scroll from a proton to the observable universe.",                           color:"#9B5DE5", tag:"educational", category:"Learn" },
  { id:"type-faster",      title:"Type Faster",          emoji:"⌨️", description:"Race against your own typing speed. Beat your record.",                      color:"#F15BB5", tag:"game",        category:"Games" },
  { id:"flag-guesser",     title:"Flag Guesser",         emoji:"🏳️", description:"How many country flags can you name in 60 seconds?",                         color:"#FEE440", tag:"trivia",      category:"Trivia" },
  { id:"breath",           title:"Breathe",              emoji:"🌬️", description:"A guided 4-7-8 breathing exercise. Just for a moment.",                     color:"#00BBF9", tag:"calm",        category:"Calm" },
  { id:"word-chain",       title:"Word Chain",           emoji:"🔗", description:"Link words — each must start with the last letter of the previous.",         color:"#06D6A0", tag:"word",        category:"Games" },
  { id:"infinite-craft",   title:"Infinite Craft",       emoji:"⚗️", description:"Combine elements to discover new ones. Powered by AI — endless possibilities.", color:"#FF9F1C", tag:"ai",        category:"AI" },

  // ── NEAL.FUN INSPIRED ────────────────────────────────────
  { id:"population-guess", title:"Population Guess",     emoji:"🌍", description:"Guess if one city or country has more people than another.",                 color:"#4ECDC4", tag:"trivia",      category:"Trivia" },
  { id:"draw-perfect",     title:"Draw a Perfect Circle",emoji:"⭕", description:"Draw the most perfect circle you can. Get rated 0–100%.",                    color:"#FF6B9D", tag:"skill",       category:"Games" },
  { id:"color-palette",    title:"Color Palette",        emoji:"🎨", description:"Match the exact hex color by adjusting RGB sliders.",                        color:"#C77DFF", tag:"skill",       category:"Games" },
  { id:"number-guess",     title:"Higher or Lower",      emoji:"🔢", description:"Is the next number higher or lower? Keep your streak going.",                color:"#F4A261", tag:"game",        category:"Games" },
  { id:"world-map-quiz",   title:"World Map Quiz",       emoji:"🗺️", description:"Click on the country shown. How many can you place correctly?",              color:"#52B788", tag:"geography",   category:"Trivia" },
  { id:"reaction-time",    title:"Reaction Time",        emoji:"⚡", description:"Click the moment the screen turns green. How fast are you?",                color:"#FFBE0B", tag:"skill",       category:"Games" },
  { id:"timeline",         title:"Timeline",             emoji:"📅", description:"Sort historical events into the correct chronological order.",               color:"#FB5607", tag:"history",     category:"Learn" },
  { id:"word-guessing",    title:"Word Warp",            emoji:"🔤", description:"Guess the hidden 5-letter word in 6 tries. A new word every day.",           color:"#8338EC", tag:"word",        category:"Games" },
  { id:"animal-quiz",      title:"Animal Kingdom",       emoji:"🦁", description:"Identify animals from descriptions and silhouettes. All 50 rounds.",         color:"#70E000", tag:"trivia",      category:"Trivia" },
  { id:"math-speed",       title:"Math Sprint",          emoji:"🧮", description:"Answer as many mental math questions as you can in 30 seconds.",             color:"#FF595E", tag:"math",        category:"Games" },
  { id:"solar-system",     title:"Solar System",         emoji:"☀️", description:"Explore and learn facts about every planet, moon, and body in our solar system.", color:"#FFD60A", tag:"educational", category:"Learn" },
  { id:"periodic-table",   title:"Periodic Table Quiz",  emoji:"🧪", description:"Identify elements from their symbol, number, or description.",               color:"#06AED5", tag:"science",     category:"Learn" },
  { id:"morse-code",       title:"Morse Decoder",        emoji:"📡", description:"Decode morse code signals. Can you crack the message?",                      color:"#80B918", tag:"skill",       category:"Games" },
  { id:"random-wiki",      title:"Wikipedia Rabbit Hole",emoji:"📖", description:"Get a random Wikipedia article and click your way to 'Philosophy' in the fewest clicks.", color:"#A8DADC", tag:"explore", category:"Fun" },
  { id:"movie-quotes",     title:"Movie Quotes",         emoji:"🎬", description:"Guess which movie the famous quote is from. 20 rounds.",                     color:"#E63946", tag:"trivia",      category:"Trivia" },
  { id:"emoji-story",      title:"Emoji Story",          emoji:"😀", description:"Turn a story into emoji — or decode a row of emoji into a movie title.",     color:"#F77F00", tag:"word",        category:"Fun" },
  { id:"memory-grid",      title:"Memory Grid",          emoji:"🧠", description:"Memorise the lit squares, then recreate the pattern. How far can you go?",   color:"#7B2FBE", tag:"memory",      category:"Games" },
  { id:"capital-cities",   title:"Capital Cities",       emoji:"🏛️", description:"Name the capital city of the given country. 195 countries to go.",          color:"#2EC4B6", tag:"geography",   category:"Trivia" },
  { id:"spin-wheel",       title:"Decision Wheel",       emoji:"🎡", description:"Add your options, spin the wheel. Let fate decide.",                         color:"#F4D35E", tag:"fun",         category:"Fun" },
  { id:"ascii-art",        title:"ASCII Art Maker",      emoji:"🖼️", description:"Turn any text into ASCII art with dozens of fonts.",                         color:"#44BBA4", tag:"creative",    category:"Fun" },
];

const BILLION_ITEMS = [
  { id:1,  name:"Cup of Coffee",          emoji:"☕",  price:5 },
  { id:2,  name:"Paperback Book",         emoji:"📚",  price:12 },
  { id:3,  name:"Movie Ticket",           emoji:"🎬",  price:15 },
  { id:4,  name:"Pizza",                  emoji:"🍕",  price:20 },
  { id:5,  name:"Uber Ride",              emoji:"🚗",  price:30 },
  { id:6,  name:"Video Game",             emoji:"🎮",  price:60 },
  { id:7,  name:"Dinner for Two",         emoji:"🍽️",  price:100 },
  { id:8,  name:"AirPods",               emoji:"🎧",  price:179 },
  { id:9,  name:"Smartphone",             emoji:"📱",  price:999 },
  { id:10, name:"MacBook Pro",            emoji:"💻",  price:2499 },
  { id:11, name:"Diamond Ring",           emoji:"💍",  price:5000 },
  { id:12, name:"Rolex Watch",            emoji:"⌚",  price:10000 },
  { id:13, name:"Horse",                  emoji:"🐴",  price:50000 },
  { id:14, name:"Tesla Model S",          emoji:"🚙",  price:89990 },
  { id:15, name:"House in Ohio",          emoji:"🏠",  price:200000 },
  { id:16, name:"Ferrari",               emoji:"🏎️",  price:300000 },
  { id:17, name:"Lamborghini",            emoji:"🏎️",  price:500000 },
  { id:18, name:"Private Jet",            emoji:"✈️",  price:3000000 },
  { id:19, name:"Superyacht",             emoji:"🛥️",  price:10000000 },
  { id:20, name:"Beverly Hills Mansion",  emoji:"🏰",  price:50000000 },
  { id:21, name:"NBA Team",               emoji:"🏀",  price:2000000000 },
];

const FLAGS_DATA = [
  {code:"US",name:"United States",       alt:["usa","america","us"],            emoji:"🇺🇸"},
  {code:"GB",name:"United Kingdom",      alt:["uk","britain","england","great britain"], emoji:"🇬🇧"},
  {code:"FR",name:"France",              alt:[],                                emoji:"🇫🇷"},
  {code:"DE",name:"Germany",             alt:["deutschland"],                   emoji:"🇩🇪"},
  {code:"JP",name:"Japan",               alt:[],                                emoji:"🇯🇵"},
  {code:"IN",name:"India",               alt:["bharat"],                        emoji:"🇮🇳"},
  {code:"CN",name:"China",               alt:["prc"],                           emoji:"🇨🇳"},
  {code:"BR",name:"Brazil",              alt:["brasil"],                        emoji:"🇧🇷"},
  {code:"CA",name:"Canada",              alt:[],                                emoji:"🇨🇦"},
  {code:"AU",name:"Australia",           alt:["oz"],                            emoji:"🇦🇺"},
  {code:"IT",name:"Italy",               alt:["italia"],                        emoji:"🇮🇹"},
  {code:"ES",name:"Spain",               alt:["espana","españa"],               emoji:"🇪🇸"},
  {code:"MX",name:"Mexico",              alt:["méxico"],                        emoji:"🇲🇽"},
  {code:"RU",name:"Russia",              alt:["russian federation"],            emoji:"🇷🇺"},
  {code:"KR",name:"South Korea",         alt:["korea"],                         emoji:"🇰🇷"},
  {code:"NG",name:"Nigeria",             alt:[],                                emoji:"🇳🇬"},
  {code:"ZA",name:"South Africa",        alt:[],                                emoji:"🇿🇦"},
  {code:"AR",name:"Argentina",           alt:[],                                emoji:"🇦🇷"},
  {code:"EG",name:"Egypt",               alt:[],                                emoji:"🇪🇬"},
  {code:"TR",name:"Turkey",              alt:["türkiye","turkiye"],             emoji:"🇹🇷"},
  {code:"SA",name:"Saudi Arabia",        alt:[],                                emoji:"🇸🇦"},
  {code:"PK",name:"Pakistan",            alt:[],                                emoji:"🇵🇰"},
  {code:"ID",name:"Indonesia",           alt:[],                                emoji:"🇮🇩"},
  {code:"TH",name:"Thailand",            alt:[],                                emoji:"🇹🇭"},
  {code:"SE",name:"Sweden",              alt:["sverige"],                       emoji:"🇸🇪"},
  {code:"NO",name:"Norway",              alt:["norge"],                         emoji:"🇳🇴"},
  {code:"NL",name:"Netherlands",         alt:["holland"],                       emoji:"🇳🇱"},
  {code:"CH",name:"Switzerland",         alt:["schweiz"],                       emoji:"🇨🇭"},
  {code:"PT",name:"Portugal",            alt:[],                                emoji:"🇵🇹"},
  {code:"GR",name:"Greece",              alt:["hellas"],                        emoji:"🇬🇷"},
  {code:"PL",name:"Poland",              alt:["polska"],                        emoji:"🇵🇱"},
  {code:"UA",name:"Ukraine",             alt:[],                                emoji:"🇺🇦"},
  {code:"ΙΕ",name:"Ireland",             alt:["eire"],                          emoji:"🇮🇪"},
  {code:"NZ",name:"New Zealand",         alt:["aotearoa","nz"],                 emoji:"🇳🇿"},
  {code:"SG",name:"Singapore",           alt:[],                                emoji:"🇸🇬"},
  {code:"MY",name:"Malaysia",            alt:[],                                emoji:"🇲🇾"},
  {code:"PH",name:"Philippines",         alt:["pilipinas"],                     emoji:"🇵🇭"},
  {code:"VN",name:"Vietnam",             alt:["viet nam"],                      emoji:"🇻🇳"},
  {code:"BD",name:"Bangladesh",          alt:[],                                emoji:"🇧🇩"},
  {code:"KE",name:"Kenya",               alt:[],                                emoji:"🇰🇪"},
];

const UNIVERSE_OBJECTS = [
  { name:"Proton",               size:"1 femtometre (10⁻¹⁵ m)",   fact:"The nucleus of a hydrogen atom." },
  { name:"Atomic Nucleus",       size:"10 femtometres",             fact:"Made of protons and neutrons." },
  { name:"Carbon Atom",          size:"154 picometres",             fact:"The building block of life." },
  { name:"DNA Double Helix",     size:"2 nanometres wide",          fact:"Holds your entire genetic code." },
  { name:"Virus",                size:"100 nanometres",             fact:"Smaller than most bacteria." },
  { name:"Bacterium",            size:"1 micrometre",               fact:"A single-celled organism." },
  { name:"Red Blood Cell",       size:"8 micrometres",              fact:"No nucleus — just haemoglobin." },
  { name:"Human Hair",           size:"70 micrometres wide",        fact:"About 1/10th of a millimetre." },
  { name:"Ant",                  size:"1–2 millimetres",            fact:"Can lift 50× their own body weight." },
  { name:"Tennis Ball",          size:"6.7 centimetres",            fact:"Must bounce 53–58 inches when dropped." },
  { name:"Human",                size:"~1.7 metres",                fact:"You are here." },
  { name:"Blue Whale",           size:"30 metres",                  fact:"Largest animal to ever exist." },
  { name:"Eiffel Tower",         size:"330 metres",                 fact:"Built in 1889 in Paris." },
  { name:"Mt. Everest",          size:"8,849 metres",               fact:"Grows ~4mm per year." },
  { name:"Earth",                size:"12,742 km diameter",         fact:"3rd rock from the Sun." },
  { name:"The Moon",             size:"3,474 km diameter",          fact:"Moving away from Earth at 3.8cm/year." },
  { name:"The Sun",              size:"1.39 million km",            fact:"Contains 99.86% of the solar system's mass." },
  { name:"Solar System",         size:"~287.5 billion km",          fact:"Edge defined by the heliopause." },
  { name:"Proxima Centauri",     size:"4.24 light-years away",      fact:"Nearest star to our Sun." },
  { name:"Milky Way",            size:"100,000 light-years wide",   fact:"Contains 100–400 billion stars." },
  { name:"Andromeda Galaxy",     size:"220,000 light-years wide",   fact:"On a collision course with the Milky Way." },
  { name:"Virgo Supercluster",   size:"~110 million light-years",   fact:"Our home supercluster." },
  { name:"Observable Universe",  size:"93 billion light-years",     fact:"The limit of what we can ever see." },
];

const TIMELINE_EVENTS = [
  { year: -3000, text:"Ancient Egypt — Pyramids of Giza built",     emoji:"🏺" },
  { year: -776,  text:"First Olympic Games in Greece",               emoji:"🏅" },
  { year: -44,   text:"Julius Caesar assassinated",                  emoji:"🗡️" },
  { year: 1066,  text:"Battle of Hastings — Norman conquest of England", emoji:"⚔️" },
  { year: 1215,  text:"Magna Carta signed",                          emoji:"📜" },
  { year: 1440,  text:"Gutenberg invents the printing press",        emoji:"📰" },
  { year: 1492,  text:"Columbus reaches the Americas",               emoji:"🚢" },
  { year: 1543,  text:"Copernicus publishes heliocentric model",     emoji:"🌍" },
  { year: 1687,  text:"Newton publishes Principia Mathematica",      emoji:"🍎" },
  { year: 1776,  text:"American Declaration of Independence",        emoji:"🗽" },
  { year: 1789,  text:"French Revolution begins",                    emoji:"🥐" },
  { year: 1859,  text:"Darwin publishes On the Origin of Species",   emoji:"🦎" },
  { year: 1869,  text:"Suez Canal opens",                            emoji:"🚢" },
  { year: 1903,  text:"Wright Brothers first powered flight",        emoji:"✈️" },
  { year: 1914,  text:"World War I begins",                          emoji:"💥" },
  { year: 1928,  text:"Alexander Fleming discovers penicillin",      emoji:"🧫" },
  { year: 1945,  text:"World War II ends",                           emoji:"🕊️" },
  { year: 1953,  text:"Structure of DNA discovered",                 emoji:"🧬" },
  { year: 1969,  text:"Neil Armstrong walks on the Moon",            emoji:"🌕" },
  { year: 1989,  text:"Berlin Wall falls",                           emoji:"🧱" },
  { year: 1991,  text:"World Wide Web invented",                     emoji:"🌐" },
  { year: 2007,  text:"First iPhone released",                       emoji:"📱" },
];

const WORDLE_WORDS = [
  "crane","slate","trace","stare","snare","share","glare","blaze","brave","crave",
  "grape","drape","shape","shake","shade","blade","blame","flame","frame","grade",
  "trade","space","place","plane","plant","blank","bland","blend","blond","blood",
  "cloud","clout","clown","crown","crowd","creak","cream","dream","dread","tread",
  "bread","break","steak","steam","steam","creep","creek","cheek","sheep","sheer",
  "steer","steel","steep","sleep","sleet","fleet","flesh","flesh","fresh","press",
  "dress","crest","chest","chess","guess","bless","bliss","crisp","twist","wrist",
  "grist","grind","grind","blind","climb","clime","crime","prime","price","pride",
  "bride","brine","bring","brink","drink","think","thick","trick","track","truck",
  "stuck","stock","block","clock","click","flick","trick","brick","prick","quick",
];

const CAPITAL_CITIES = [
  {country:"France",        capital:"Paris",         emoji:"🇫🇷"},
  {country:"Japan",         capital:"Tokyo",          emoji:"🇯🇵"},
  {country:"Australia",     capital:"Canberra",       emoji:"🇦🇺"},
  {country:"Brazil",        capital:"Brasilia",       emoji:"🇧🇷"},
  {country:"Canada",        capital:"Ottawa",         emoji:"🇨🇦"},
  {country:"Germany",       capital:"Berlin",         emoji:"🇩🇪"},
  {country:"India",         capital:"New Delhi",      emoji:"🇮🇳"},
  {country:"China",         capital:"Beijing",        emoji:"🇨🇳"},
  {country:"Russia",        capital:"Moscow",         emoji:"🇷🇺"},
  {country:"Argentina",     capital:"Buenos Aires",   emoji:"🇦🇷"},
  {country:"Egypt",         capital:"Cairo",          emoji:"🇪🇬"},
  {country:"Nigeria",       capital:"Abuja",          emoji:"🇳🇬"},
  {country:"South Africa",  capital:"Pretoria",       emoji:"🇿🇦"},
  {country:"Mexico",        capital:"Mexico City",    emoji:"🇲🇽"},
  {country:"Italy",         capital:"Rome",           emoji:"🇮🇹"},
  {country:"Spain",         capital:"Madrid",         emoji:"🇪🇸"},
  {country:"Portugal",      capital:"Lisbon",         emoji:"🇵🇹"},
  {country:"Netherlands",   capital:"Amsterdam",      emoji:"🇳🇱"},
  {country:"Sweden",        capital:"Stockholm",      emoji:"🇸🇪"},
  {country:"Norway",        capital:"Oslo",           emoji:"🇳🇴"},
  {country:"Switzerland",   capital:"Bern",           emoji:"🇨🇭"},
  {country:"Greece",        capital:"Athens",         emoji:"🇬🇷"},
  {country:"Turkey",        capital:"Ankara",         emoji:"🇹🇷"},
  {country:"Saudi Arabia",  capital:"Riyadh",         emoji:"🇸🇦"},
  {country:"South Korea",   capital:"Seoul",          emoji:"🇰🇷"},
  {country:"Thailand",      capital:"Bangkok",        emoji:"🇹🇭"},
  {country:"Indonesia",     capital:"Jakarta",        emoji:"🇮🇩"},
  {country:"Philippines",   capital:"Manila",         emoji:"🇵🇭"},
  {country:"Vietnam",       capital:"Hanoi",          emoji:"🇻🇳"},
  {country:"New Zealand",   capital:"Wellington",     emoji:"🇳🇿"},
  {country:"Kenya",         capital:"Nairobi",        emoji:"🇰🇪"},
  {country:"Pakistan",      capital:"Islamabad",      emoji:"🇵🇰"},
  {country:"Bangladesh",    capital:"Dhaka",          emoji:"🇧🇩"},
  {country:"Ukraine",       capital:"Kyiv",           emoji:"🇺🇦"},
  {country:"Poland",        capital:"Warsaw",         emoji:"🇵🇱"},
  {country:"Ireland",       capital:"Dublin",         emoji:"🇮🇪"},
  {country:"Malaysia",      capital:"Kuala Lumpur",   emoji:"🇲🇾"},
  {country:"Singapore",     capital:"Singapore",      emoji:"🇸🇬"},
  {country:"United Kingdom",capital:"London",         emoji:"🇬🇧"},
  {country:"United States", capital:"Washington D.C.",emoji:"🇺🇸"},
];

const MOVIE_QUOTES = [
  { quote:"May the Force be with you.", movie:"Star Wars", year:1977 },
  { quote:"I'll be back.", movie:"The Terminator", year:1984 },
  { quote:"You can't handle the truth!", movie:"A Few Good Men", year:1992 },
  { quote:"There's no place like home.", movie:"The Wizard of Oz", year:1939 },
  { quote:"Houston, we have a problem.", movie:"Apollo 13", year:1995 },
  { quote:"Why so serious?", movie:"The Dark Knight", year:2008 },
  { quote:"To infinity and beyond!", movie:"Toy Story", year:1995 },
  { quote:"Just keep swimming.", movie:"Finding Nemo", year:2003 },
  { quote:"I am your father.", movie:"The Empire Strikes Back", year:1980 },
  { quote:"Life is like a box of chocolates.", movie:"Forrest Gump", year:1994 },
  { quote:"I see dead people.", movie:"The Sixth Sense", year:1999 },
  { quote:"Here's looking at you, kid.", movie:"Casablanca", year:1942 },
  { quote:"Elementary, my dear Watson.", movie:"Sherlock Holmes", year:2009 },
  { quote:"You're gonna need a bigger boat.", movie:"Jaws", year:1975 },
  { quote:"They may take our lives, but they'll never take our freedom!", movie:"Braveheart", year:1995 },
  { quote:"With great power comes great responsibility.", movie:"Spider-Man", year:2002 },
  { quote:"Keep your friends close, but your enemies closer.", movie:"The Godfather Part II", year:1974 },
  { quote:"It's alive! It's alive!", movie:"Frankenstein", year:1931 },
  { quote:"I volunteer as tribute.", movie:"The Hunger Games", year:2012 },
  { quote:"Just when I thought I was out, they pull me back in.", movie:"The Godfather Part III", year:1990 },
];

const POPULATION_PAIRS = [
  { a:{ name:"India", pop:1428000000 }, b:{ name:"China", pop:1425000000 } },
  { a:{ name:"USA",   pop:335000000  }, b:{ name:"Indonesia", pop:277000000 } },
  { a:{ name:"Tokyo", pop:37000000   }, b:{ name:"Delhi", pop:33000000 } },
  { a:{ name:"Brazil",pop:214000000  }, b:{ name:"Pakistan", pop:230000000 } },
  { a:{ name:"Nigeria",pop:220000000 }, b:{ name:"Russia", pop:143000000 } },
  { a:{ name:"Germany",pop:84000000  }, b:{ name:"UK", pop:68000000 } },
  { a:{ name:"France", pop:68000000  }, b:{ name:"Thailand", pop:71000000 } },
  { a:{ name:"Australia",pop:26000000}, b:{ name:"Netherlands", pop:17000000 } },
  { a:{ name:"Canada", pop:38000000  }, b:{ name:"Saudi Arabia", pop:36000000 } },
  { a:{ name:"Mexico", pop:128000000 }, b:{ name:"Ethiopia", pop:126000000 } },
  { a:{ name:"Istanbul",pop:15000000 }, b:{ name:"Moscow", pop:12000000 } },
  { a:{ name:"Seoul",  pop:10000000  }, b:{ name:"London", pop:9000000 } },
  { a:{ name:"Buenos Aires",pop:15000000}, b:{ name:"Lagos", pop:14000000 } },
  { a:{ name:"Egypt",  pop:105000000 }, b:{ name:"Vietnam", pop:97000000 } },
  { a:{ name:"Iran",   pop:87000000  }, b:{ name:"Turkey", pop:85000000 } },
];

const ANIMALS_DATA = [
  { name:"African Elephant", emoji:"🐘", clue:"World's largest land animal. Has no natural predators as an adult." },
  { name:"Blue Whale",        emoji:"🐋", clue:"Largest animal to ever exist. Its heartbeat can be detected 2 miles away." },
  { name:"Cheetah",           emoji:"🐆", clue:"Fastest land animal — can sprint at 70 mph. Cannot roar." },
  { name:"Platypus",          emoji:"🦆", clue:"Venomous, lays eggs, has a duck bill — yet it's a mammal." },
  { name:"Octopus",           emoji:"🐙", clue:"Has 3 hearts, blue blood, and can change colour instantly." },
  { name:"Giraffe",           emoji:"🦒", clue:"Tallest animal. Has the same number of neck vertebrae as a human." },
  { name:"Axolotl",           emoji:"🦎", clue:"Can regrow lost limbs, including parts of its heart and brain." },
  { name:"Tardigrade",        emoji:"🐛", clue:"Microscopic animal that can survive in space and extreme radiation." },
  { name:"Mantis Shrimp",     emoji:"🦐", clue:"Can punch with the force of a bullet and see 16 types of colour." },
  { name:"Mimic Octopus",     emoji:"🐙", clue:"Can impersonate flounders, lionfish, and sea snakes to fool predators." },
  { name:"Narwhal",           emoji:"🦄", clue:"Its 'horn' is actually a tusk — a giant tooth that grows through its lip." },
  { name:"Immortal Jellyfish", emoji:"🪼", clue:"Can revert to its juvenile state after reaching adulthood — effectively immortal." },
  { name:"Pistol Shrimp",     emoji:"🦐", clue:"Snaps its claw so fast it creates a plasma bubble hotter than the sun's surface." },
  { name:"Lyrebird",          emoji:"🐦", clue:"Can perfectly mimic chainsaw sounds, camera shutters, and other birds." },
  { name:"Honeybee",          emoji:"🐝", clue:"Can communicate the location of flowers through a 'waggle dance'." },
];

const SOLAR_SYSTEM_DATA = [
  { name:"Mercury", emoji:"☿",  color:"#b5b5b5", distanceAU:0.39, diameterKm:4879,  moons:0,    tempC:"430 day / -180 night", fact:"No atmosphere. A year lasts just 88 Earth days." },
  { name:"Venus",   emoji:"♀️", color:"#e8cda0", distanceAU:0.72, diameterKm:12104, moons:0,    tempC:"462 avg",              fact:"Hottest planet. Rotates backward and very slowly." },
  { name:"Earth",   emoji:"🌍", color:"#4fa3e0", distanceAU:1.00, diameterKm:12742, moons:1,    tempC:"15 avg",               fact:"Only known planet to harbour life." },
  { name:"Mars",    emoji:"♂️", color:"#c1440e", distanceAU:1.52, diameterKm:6779,  moons:2,    tempC:"-60 avg",              fact:"Home to Olympus Mons — the tallest volcano in the solar system." },
  { name:"Jupiter", emoji:"♃",  color:"#c88b3a", distanceAU:5.20, diameterKm:142984,moons:95,   tempC:"-110 avg",             fact:"The Great Red Spot has been raging for 350+ years." },
  { name:"Saturn",  emoji:"♄",  color:"#e4d191", distanceAU:9.58, diameterKm:120536,moons:146,  tempC:"-140 avg",             fact:"Its rings are made of ice and rock — and are only 10m thick." },
  { name:"Uranus",  emoji:"⛢",  color:"#7de8e8", distanceAU:19.2, diameterKm:51118, moons:28,   tempC:"-195 avg",             fact:"Rotates on its side. Its poles get 42 years of continuous night." },
  { name:"Neptune", emoji:"♆",  color:"#3f54ba", distanceAU:30.1, diameterKm:49528, moons:16,   tempC:"-200 avg",             fact:"Strongest winds in the solar system — 2,100 km/h." },
];

const ELEMENTS_DATA = [
  { symbol:"H",  name:"Hydrogen",   number:1,  category:"Nonmetal",        emoji:"💧" },
  { symbol:"He", name:"Helium",     number:2,  category:"Noble Gas",       emoji:"🎈" },
  { symbol:"C",  name:"Carbon",     number:6,  category:"Nonmetal",        emoji:"💎" },
  { symbol:"N",  name:"Nitrogen",   number:7,  category:"Nonmetal",        emoji:"💨" },
  { symbol:"O",  name:"Oxygen",     number:8,  category:"Nonmetal",        emoji:"🌬️" },
  { symbol:"Na", name:"Sodium",     number:11, category:"Alkali Metal",    emoji:"🧂" },
  { symbol:"Mg", name:"Magnesium",  number:12, category:"Alkaline Earth",  emoji:"✨" },
  { symbol:"Al", name:"Aluminium",  number:13, category:"Post-transition", emoji:"🥤" },
  { symbol:"Si", name:"Silicon",    number:14, category:"Metalloid",       emoji:"💻" },
  { symbol:"P",  name:"Phosphorus", number:15, category:"Nonmetal",        emoji:"🔥" },
  { symbol:"S",  name:"Sulfur",     number:16, category:"Nonmetal",        emoji:"🌋" },
  { symbol:"Cl", name:"Chlorine",   number:17, category:"Halogen",         emoji:"🏊" },
  { symbol:"K",  name:"Potassium",  number:19, category:"Alkali Metal",    emoji:"🍌" },
  { symbol:"Ca", name:"Calcium",    number:20, category:"Alkaline Earth",  emoji:"🦷" },
  { symbol:"Fe", name:"Iron",       number:26, category:"Transition Metal",emoji:"🔩" },
  { symbol:"Ni", name:"Nickel",     number:28, category:"Transition Metal",emoji:"🪙" },
  { symbol:"Cu", name:"Copper",     number:29, category:"Transition Metal",emoji:"🍂" },
  { symbol:"Zn", name:"Zinc",       number:30, category:"Transition Metal",emoji:"🔧" },
  { symbol:"Ag", name:"Silver",     number:47, category:"Transition Metal",emoji:"🥈" },
  { symbol:"Au", name:"Gold",       number:79, category:"Transition Metal",emoji:"🥇" },
  { symbol:"Hg", name:"Mercury",    number:80, category:"Transition Metal",emoji:"🌡️" },
  { symbol:"Pb", name:"Lead",       number:82, category:"Post-transition", emoji:"🔋" },
  { symbol:"U",  name:"Uranium",    number:92, category:"Actinide",        emoji:"☢️" },
];

const MORSE_MESSAGES = [
  { message:"HELLO",  morse:".... . .-.. .-.. ---" },
  { message:"WORLD",  morse:".-- --- .-. .-.. -.." },
  { message:"SOS",    morse:"... --- ..." },
  { message:"HAMMER", morse:".... .- -- -- . .-." },
  { message:"BRAIN",  morse:"-... .-. .- .. -." },
  { message:"EARTH",  morse:". .- .-. - ...." },
  { message:"SPACE",  morse:"... .--. .- -.-. ." },
  { message:"JAVA",   morse:".--- .- ...- .-" },
  { message:"MUSIC",  morse:"-- ..- ... .. -.-." },
  { message:"DREAM",  morse:"-.. .-. . .- --" },
];

const TYPING_TEXTS = [
  "The quick brown fox jumps over the lazy dog near the riverside at dawn.",
  "Pack my box with five dozen liquor jugs for the evening party tonight.",
  "How vexingly quick daft zebras jump over the enormous wooden fence today.",
  "The five boxing wizards jump quickly over the large brown fence at noon.",
  "Amazingly few discotheques provide jukeboxes that sound quite this magnificent.",
  "We promptly judged antique ivory buckles for the next prize show exhibition.",
  "A wizard's job is to vex chumps quickly in fog, without being detected.",
  "Sphinx of black quartz, judge my vow before the clock strikes midnight.",
];

const ASCII_FONTS = {
  "Block": (t) => {
    const chars = {
      A:"/ \\|---|   ",B:"|--\\|--/|--/",C:" --||  | --",
      E:"|--||-- |--",H:"|  ||---|  |",I:"---| |  ---",
      L:"|  ||  ||--",M:"|\\/||  ||  |",N:"|\\| || \\||  |",
      O:" - || || - ",R:"|--||\\  |  |",S:" --||--|-- ",
      T:"---| |  | |",U:"|  ||  | -- ",W:"|  ||/\\||  |",
    };
    return t.toUpperCase().split('').map(c => chars[c]||"   |   |   ").join('|');
  }
};

const WIKI_TOPICS = [
  "Quantum mechanics","The Renaissance","Black holes","Ancient Rome","Jazz music",
  "The Amazon rainforest","Artificial intelligence","The Roman Empire","Plate tectonics",
  "The French Revolution","Photosynthesis","The Cold War","DNA","The Internet",
  "Climate change","The Olympics","Shakespeare","Volcanoes","Cryptocurrency","Evolution",
];
